"""empty message

Revision ID: 5bda08391a52
Revises: 
Create Date: 2022-04-04 20:19:38.986822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bda08391a52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Cocktails')
    op.drop_table('Raiting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Raiting',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Raiting_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Raiting_pkey'),
    sa.UniqueConstraint('author', name='Raiting_author_key'),
    sa.UniqueConstraint('title', name='Raiting_title_key')
    )
    op.create_table('Cocktails',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Cocktails_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recipe', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ingredient', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tools', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Cocktails_pkey'),
    sa.UniqueConstraint('image', name='Cocktails_image_key'),
    sa.UniqueConstraint('title', name='Cocktails_title_key'),
    sa.UniqueConstraint('url', name='Cocktails_url_key')
    )
    # ### end Alembic commands ###
