"""added ingredients to cocktails

Revision ID: c449872926f0
Revises: 5222f59d15aa
Create Date: 2022-08-07 17:06:28.359405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c449872926f0'
down_revision = '5222f59d15aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cocktails', ['id'])
    op.create_unique_constraint(None, 'ingredients', ['id'])
    op.create_unique_constraint(None, 'recipe', ['id'])
    op.create_unique_constraint(None, 'tags', ['id'])
    op.add_column('tools', sa.Column('tool', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'tools', ['id'])
    op.drop_column('tools', 'tools')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('tools', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tools', type_='unique')
    op.drop_column('tools', 'tool')
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'recipe', type_='unique')
    op.drop_constraint(None, 'ingredients', type_='unique')
    op.drop_constraint(None, 'cocktails', type_='unique')
    # ### end Alembic commands ###
